baseURL = "https://Kaihchs118.github.io/kai_studio/"
languageCode = "zh-TW"
title = "KAI STUDIO"
theme = "PaperMod"

[params]
  showReadingTime = true
  showBreadCrumbs = true
  showPostNavLinks = true
  showCodeCopyButtons = true
  customCSS = ["assets/css/custom.css"]
  [params.assets]
    favicon = "img/demo1.png"

  [params.homeInfoParams]
    Title = "歡迎來到KAI STUDIO"
    Content = "找看看你想要看的文章" 
[menu]
  [[menu.main]]
    identifier = "home"
    name = "首頁"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "關於我"
    url = "/about/"
    weight = 4

  [[menu.main]]
    identifier = "tag"
    name = "標題"
    url = "/Tag/"
    weight = 3