baseURL = "https://Kaihchs118.github.io/kai_studio/"
languageCode = "zh-TW"
title = "KAI STUDIO"
theme = "PaperMod"

[params]
  showReadingTime = true
  showBreadCrumbs = true
  showPostNavLinks = true
  showCodeCopyButtons = true
  showSearch = true
  searchPlaceholder = "搜尋文章..."
  [params.menu]
  enableSearch = true
  [params.assets]
    favicon = "img/demo1.png"

  [params.homeInfoParams]
    Title = "歡迎來到KAI STUDIO"
    Content = "Kai Studio"

[menu]

  [[menu.main]]
  identifier = "home"
  name = "首頁"
  url = "/"
  weight = 1

  [[menu.main]]
  identifier = "posts"
  name = "文章"
  url = "/posts/"
  weight = 2

  [[menu.main]]
  identifier = "categories"
  name = "分類"
  url = "/categories/"
  weight = 3

  [[menu.main]]
  identifier = "tags"
  name = "標籤"
  url = "/tags/"
  weight = 4
  [[menu.main]]
  identifier = "search"
  name = "搜尋"
  url = "#"
  weight = 5
  pre = "<i class='fas fa-search'></i>"

  [[menu.main]]
  identifier = "about"
  name = "關於我"
  url = "/about/"
  weight = 6