baseURL = "https://Kaihchs118.github.io/kai_studio/"
languageCode = "zh-TW"
title = "KAI STUDIO"
theme = "PaperMod"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  showReadingTime = true
  showBreadCrumbs = true
  showPostNavLinks = true
  showCodeCopyButtons = true
  customCSS = ["css/custom.css"]

  [params.assets]
    favicon = "img/demo1.png"

  [params.homeInfoParams]
    Title = "歡迎來到KAI STUDIO"
    Content = "Kai Studio"

[menu]

  [[menu.main]]
  identifier = "home"
  name = "首頁"
  url = "/"
  weight = 1

  [[menu.main]]
  identifier = "posts"
  name = "文章"
  url = "/posts/"
  weight = 2

  [[menu.main]]
  identifier = "categories"
  name = "分類"
  url = "/categories/"
  weight = 3

  [[menu.main]]
  identifier = "tags"
  name = "標籤"
  url = "/tags/"
  weight = 4


  [[menu.main]]
  identifier = "about"
  name = "關於我"
  url = "/about/"
  weight = 6
  
  [[menu.main]]
  identifier = "first-visit"
  name = "第一次進來點我"
  url = "/First.md/"
  weight = 7
