baseURL = "https://Kaihchs118.github.io/kai_studio/"
languageCode = "zh-TW"
title = "KAI STUDIO"
theme = "PaperMod"

[params]
  showReadingTime = true
  showBreadCrumbs = true
  showPostNavLinks = true
  showCodeCopyButtons = true

  [params.assets]
    favicon = "img/demo1.png"

  [params.homeInfoParams]
    Title = "歡迎來到KAI STUDIO"
    Content = "Scroll Down ..."