name: Deploy Hugo site to GitHub Pages

on:
  # 1️⃣ 當 main 分支有 push 時觸發
  push:
    branches:
      - main  # 注意：請改成你的預設分支名稱

  # 2️⃣ 手動觸發
  workflow_dispatch:

  # 3️⃣ 定時排程（每天 UTC 00:00 執行一次）
  schedule:
    - cron: '0 0 * * *'  # UTC 時間，每天零點執行一次

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          # extended: true # 如果主題需要 Hugo Extended，取消註解

      - name: Build the site
        # 🔑 加上 --buildFuture 讓未來日期文章也生成
        run: hugo --minify --buildFuture

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.pages.outputs.base_url }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment