name: Build and Deploy Hugo site

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive  # 如果 theme 是 submodule 才需要，否則也沒差
          persist-credentials: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.128.0'   # 換成你本地的 hugo version

      - name: Build site
        run: hugo --minify

      - name: Deploy to docs folder
        run: |
          rm -rf docs || true
          mkdir docs
          cp -a public/. docs/

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "chore: update site [skip ci]" || echo "No changes to commit"
          git push origin main
